[package]
name = "mori"
version = "1.0.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.5.0"
rand = "0.8.5"
ureq = "2.10.1"
urlencoding = "2.1.3"
enet = { git = "https://github.com/CLOEI/enet-rs.git" }
paris = { version = "1.5", features = ["timestamps", "macros", "no_logger"] }
sha2 = "0.10.8"
md5 = "0.7.0"
hex = "0.4.3"
