[package]
name = "Mori"
version = "1.0.0"
edition = "2021"

[dependencies]
# tokio = { version = "1.38.0", features = ["full"] }
# chromiumoxide = { version = "0.7.0", features = [
#   "tokio-runtime",
# ], default-features = false }
bincode = "1.3.3"
byteorder = "1.5.0"
rand = "0.8.5"
ureq = { version = "2.10.1", features = ["cookies", "json"] }
urlencoding = "2.1.3"
rusty_enet = { git = "https://github.com/CLOEI/rusty_enet.git" }
paris = { version = "1.5", features = ["timestamps", "macros", "no_logger"] }
sha2 = "0.10.8"
md5 = "0.7.0"
hex = "0.4.3"
regex = "1.10.6"
serde_json = "1.0.125"
base64 = "0.22.1"
futures = "0.3.30"
serde = { version = "1.0.208", features = ["derive"] }
serde_repr = "0.1.19"
gtitem-r = { git = "https://github.com/CLOEI/gtitem-r.git" }
gtworld-r = { git = "https://github.com/CLOEI/gtworld-r.git" }
eframe = "0.28.1"
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "0.25.2", features = ["png"] }
egui = "0.28.1"
parking_lot = { version = "0.12.3", features = ["deadlock_detection"] }
socks = "0.3.4"
steamworks = "0.11.0"
