[package]
name = "mate"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
fantoccini = "0.19.3"
regex = "1.10.5"
spdlog-rs = "0.3.13"
ureq = "2.10.0"
